### ISSUE TITLE
other map don't load or have a issue

### ISSUE THREAD

**Issue by Novamiiro** [matheuh/rage-level#2]
![20191229195026_1](https://user-images.githubusercontent.com/29163912/71561530-036ae280-2a78-11ea-9e81-31f24bf3fd02.jpg)
![20191227192033_1](https://user-images.githubusercontent.com/29163912/71545947-c9271580-2991-11ea-8add-fd810f220bb7.jpg)
![20191227192140_1](https://user-images.githubusercontent.com/29163912/71545949-cc220600-2991-11ea-964e-7c0b3d82f7c3.jpg)
![20191229115102_1](https://user-images.githubusercontent.com/29163912/71556922-c7675b80-2a3e-11ea-8c53-d17e1962cfcd.jpg)

**Comment by PERPGamer** [comment]
Is it just me or does Pillbox hospital has messed up collisions?

**Comment by LaFouine25** [comment]
Hi,

You can add an issue at Sandy Shore, at the Sherrif.
![image](https://user-images.githubusercontent.com/5525394/71585705-ceae6800-2b17-11ea-90d6-9ff68647a3e7.png)

**Comment by Blitzzer63** [comment]
![Capture](https://user-images.githubusercontent.com/19784124/71629174-66858200-2bfc-11ea-8f83-d294f5f5c920.PNG)

**Comment by MoleDJ** [comment]
i saw that map bug of behind the bridge in every casino map I tested

**Comment by matheuh** [comment]
Hey everyone,
Don't worry, i am coming back with a lot of new MLOS like Vespucci Police Departement, Prison, Houses, Mansions etc.. AND FIXED THINGS !
Stay tuned boys !

**Comment by iTexZoz** [comment]
Create emtpy server and gitclone rage-level, and retry. if you have issue comment this.
