### ISSUE TITLE
[Request] a list of wich map is in each folder.

### ISSUE THREAD

**Issue by MoleDJ** [matheuh/rage-level#3]
Hi, can you please add some txt witrh the equivalence of each stream folder wich map it is? sure you have something like that already ;)

**Comment by iTexZoz** [comment]
Hello, use that, for show in game additional content https://github.com/iTexZoz/RageLevel-Menu

**Comment by MoleDJ** [comment]
Oh nono, what i mean is know in each numbered folder you have wich map it is, in case i want to remove some of the maps in my server

**Comment by iTexZoz** [comment]
This is unannounced and will not be available at this time, however you can play around with OpenIV to figure out which folder and link to which content.
