### ISSUE TITLE
issue in map

### ISSUE THREAD

**Issue by Novamiiro** [matheuh/rage-level#5]
![20200127192450_1](https://user-images.githubusercontent.com/29163912/73202147-bd6a7280-413a-11ea-9313-e60b81dd5a79.jpg)
![20200127191647_1](https://user-images.githubusercontent.com/29163912/73201977-6c5a7e80-413a-11ea-842a-7d77c20b6799.jpg)

**Comment by iTexZoz** [comment]
Not issue with Rage-Level.

**Comment by Novamiiro** [comment]
But i don't have another Map and if i don't start Rage-Level i don't have this problem

**Comment by Novamiiro** [comment]
And i test in a empty server it's the same

**Comment by iTexZoz** [comment]
Use Rage-Level and bob64_ip. working fine

**Comment by Novamiiro** [comment]
it's not working for me it's same

**Comment by Novamiiro** [comment]
dosn't work for me but if i stop Rage-Level the problem is done

**Comment by Novamiiro** [comment]
so i don't know

**Comment by Novamiiro** [comment]
You can't help me with that problem so ?because i see that problem in a lot of server
